=== marcospdsf/EOT/data/conf/creatures.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
		targetNamespace="stendhal" xmlns:tns="http://www.example.org/creatures"
		elementFormDefault="qualified" xmlns:Q2="stendhal">

	<xsd:element name="creatures" type="Q2:CreaturesType"></xsd:element>

	<xsd:complexType name="CreaturesType">
		<xsd:sequence>
			<xsd:element name="creature" type="Q2:CreatureType"
				minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="CreatureType">
		<xsd:sequence>
			<xsd:element name="type" type="Q2:Type" minOccurs="1"/>
			<xsd:element name="hidden" type="xsd:string" minOccurs="0"/>
			<xsd:element name="description" type="xsd:string" minOccurs="0"/>
			<xsd:element name="attributes" type="Q2:Attributes" minOccurs="1"/>
			<xsd:element name="level" type="Q2:Level" minOccurs="1"/>
			<xsd:element name="experience" type="Q2:Experience" minOccurs="1"/>
			<xsd:element name="respawn" type="Q2:Respawn"/>
			<xsd:element name="blood" type="Q2:Blood" minOccurs="0"/>
			<xsd:element name="corpse" type="Q2:Corpse"/>
			<xsd:element name="drops" type="Q2:Drops" minOccurs="0"/>
			<xsd:element name="slots" type="Q2:Slots" minOccurs="0"/>
			<xsd:element name="equips" type="Q2:Equips" minOccurs="0"/>
			<xsd:element name="abilities" type="Q2:Abilities" minOccurs="0"/>
			<xsd:element name="ai" type="Q2:Ai" minOccurs="1"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string"/>
		<xsd:attribute name="condition" type="xsd:string" use="optional"/>
	</xsd:complexType>

	<xsd:complexType name="Item">
		<xsd:attribute name="value" type="xsd:string"/>
		<xsd:attribute name="quantity" type="xsd:string"/>
		<xsd:attribute name="probability" type="xsd:double"/>
	</xsd:complexType>

	<xsd:complexType name="SpecialItem">
		<xsd:attribute name="value" type="xsd:string" use="required"/>
		<xsd:attribute name="note" type="xsd:string" use="optional"/>
	</xsd:complexType>

	<xsd:complexType name="Drops">
		<xsd:sequence>
			<xsd:element name="item" type="Q2:Item" minOccurs="0"
				maxOccurs="unbounded"/>
			<xsd:element name="special" type="Q2:SpecialItem" minOccurs="0"
				maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Respawn">
		<xsd:sequence>
		</xsd:sequence>
		<xsd:attribute name="value" type="xsd:positiveInteger"/>
	</xsd:complexType>

	<xsd:complexType name="Blood">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="Corpse">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="width" type="xsd:positiveInteger"/>
		<xsd:attribute name="height" type="xsd:positiveInteger"/>
		<xsd:attribute name="harmless" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Attributes">
		<xsd:sequence>
			<xsd:element name="atk" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="ratk" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="def" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="hp" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="speed" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:decimal"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="size" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="noise" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="state" type="xsd:string"/>
					<xsd:attribute name="value" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="resistance" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="visibility" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Ai">
		<xsd:sequence>
			<xsd:element name="says" type="Q2:Says" minOccurs="0"/>
			<xsd:element name="profile" type="Q2:Profile" minOccurs="1"
				maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Says">
		<xsd:sequence>
			<xsd:element name="noise" type="Q2:Text" minOccurs="0"
				maxOccurs="unbounded"/>
			<xsd:element name="text" type="Q2:Text" minOccurs="0"
				maxOccurs="unbounded"/>
			<xsd:element name="sound" type="Q2:Sound" minOccurs="0"
				maxOccurs="unbounded"/>
			<xsd:element name="movement" type="Q2:Movement" minOccurs="0"
				maxOccurs="unbounded"/>
			<xsd:element name="death" type="Q2:Death" minOccurs="0"
				maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Text">
		<xsd:attribute name="value" type="xsd:string"/>
		<xsd:attribute name="state" type="xsd:string"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="Sound">
		<xsd:attribute name="value" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Movement">
		<xsd:attribute name="value" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Death">
		<xsd:attribute name="value" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Profile">
		<xsd:attribute name="name" type="xsd:string"/>
		<xsd:attribute name="params" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Type">
		<xsd:attribute name="class" type="xsd:string"/>
		<xsd:attribute name="subclass" type="xsd:string"/>
		<xsd:attribute name="shadow" type="xsd:string"/>
		<xsd:attribute name="tileid" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Level">
		<xsd:attribute name="value" type="xsd:integer"/>
	</xsd:complexType>

	<xsd:complexType name="Experience">
		<xsd:attribute name="value" type="xsd:integer"/>
	</xsd:complexType>

	<xsd:complexType name="Slots">
		<xsd:sequence>
			<xsd:element name="slot" type="xsd:string" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Equips">
		<xsd:sequence>
			<xsd:element name="slot" type="Q2:Slot" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Abilities">
		<xsd:sequence>
			<xsd:element name="damage" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="type" type="xsd:string" default="cut"/>
					<xsd:attribute name="rangedType" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="susceptibility" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:attribute name="type" type="xsd:string"/>
					<xsd:attribute name="value" type="xsd:decimal"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="statusattack" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:attribute name="type" type="xsd:string"/>
					<xsd:attribute name="value" type="xsd:decimal"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Slot">
		<xsd:sequence>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="item" type="xsd:string" use="required"/>
		<xsd:attribute name="quantity" type="xsd:positiveInteger"/>
	</xsd:complexType>

</xsd:schema>

=== marcospdsf/EOT/data/conf/creatures/pol_ptaki.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../creatures.xsd ">

	<!-- START: ptaki -->

	<creature name="city pigeon">
		<type class="pol/ptaki" subclass="golabek" tileid="pol_ptaki.png:0"/>
		<description>You see a little pigeon with a sharp beak, looking for breadcrumbs!</description>
		<attributes>
			<atk value="3"/>
			<def value="9"/>
			<hp value="12"/>
			<speed value="0.4"/>
			<size value="1,1"/>
		</attributes>
		<level value="1"/>
		<experience value="8"/>
		<respawn value="700"/>
		<corpse name="corpse"/>
		<drops>
			<item value="chicken" quantity="[1,1]" probability="80.0"/>
		</drops>
		<ai>
			<says>
				<sound value="pol-bird_pigeon"/>
			</says>
			<profile name="coward"/>
			<profile name="animal"/>
			<profile name="offensive"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="seagull">
		<type class="pol/ptaki" subclass="mewa" tileid="pol_ptaki.png:2"/>
		<description>You see a screeching seagull.</description>
		<attributes>
			<atk value="15"/>
			<def value="9"/>
			<hp value="56"/>
			<speed value="0.8"/>
			<size value="1,1"/>
		</attributes>
		<level value="3"/>
		<experience value="30"/>
		<respawn value="999"/>
		<corpse name="corpse"/>
		<drops>
			<item value="sandwich" quantity="[1,1]" probability="2.0"/>
			<item value="cod" quantity="[1,1]" probability="20.0"/>
			<item value="perch" quantity="[1,1]" probability="10.0"/>
		</drops>
		<ai>
			<says>
				<sound value="pol-seagull"/>
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="raven">
		<type class="pol/ptaki" subclass="kruk" tileid="pol_ptaki.png:1"/>
		<description>You see an intelligent black raven.</description>
		<attributes>
			<atk value="20"/>
			<def value="11"/>
			<hp value="64"/>
			<speed value="0.8"/>
			<size value="1,1"/>
		</attributes>
		<level value="6"/>
		<experience value="62"/>
		<respawn value="904"/>
		<corpse name="corpse"/>
		<drops>
			<item value="cheese" quantity="[1,1]" probability="100.0"/>
			<item value="goat cheese" quantity="[1,1]" probability="5.0"/>
		</drops>
		<ai>
			<says>
				<sound value="pol-crow" />
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="hawk">
		<type class="pol/ptaki" subclass="jastrzab" tileid="pol_ptaki.png:3"/>
		<description>You see a sharp-eyed hunting hawk.</description>
		<attributes>
			<atk value="33"/>
			<def value="99"/>
			<hp value="127"/>
			<speed value="0.8"/>
			<size value="1,1"/>
		</attributes>
		<level value="21"/>
		<experience value="302"/>
		<respawn value="999"/>
		<corpse name="corpse"/>
		<drops>
			<item value="chicken" quantity="[1,1]" probability="80.0"/>
		</drops>
		<ai>
			<says>
				<sound value="pol-hawk1"/>
				<sound value="pol-hawk2"/>
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<!-- END: ptaki -->

</creatures>

=== marcospdsf/EOT/data/conf/creatures/pol_pasterze_drzew.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../creatures.xsd ">

	<!-- START: pasterze -->

	<creature name="treant shepherd">
		<type class="pol/pasterze_drzew" subclass="pasterz_drzew" tileid="pol_pasterze_drzew.png:0"/>
		<description>You see an ancient treant shepherd guarding the deep forests.</description>
		<attributes>
			<atk value="919"/>
			<def value="193"/>
			<hp value="1250"/>
			<speed value="0.1"/>
			<size value="2,2"/>
		</attributes>
		<level value="213"/>
		<experience value="20000"/>
		<respawn value="6200"/>
		<corpse name="flora_ent" width="2" height="1"/>
		<drops>
			<item value="wood" quantity="[1,4]" probability="22.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="heal" params="30,50"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<!-- END: pasterze -->

</creatures>

=== marcospdsf/EOT/data/conf/creatures/faumonia_duchy.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../creatures.xsd ">

	<creature name="faceless phantom">
		<type class="faumonia_duchy" subclass="faceless_ghost" tileid="faumonia_duchy.png:0"/>
		<description>You see a faceless phantom drifting eerily.</description>
		<attributes>
			<atk value="161"/>
			<def value="21"/>
			<hp value="140"/>
			<speed value="0.4"/>
			<size value="1,1"/>
		</attributes>
		<level value="27"/>
		<experience value="1000"/>
		<respawn value="1500"/>
		<corpse name="puddle_light_blue"/>
		<drops>
			<item value="money" quantity="[3,30]" probability="90.0"/>
			<item value="antidote" quantity="[1,1]" probability="60.0"/>
			<item value="blood robe" quantity="[1,1]" probability="1.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>
	
	<creature name="elven ghost">
		<type class="faumonia_duchy" subclass="elf_ghost" tileid="faumonia_duchy.png:1"/>
		<description>You see the wandering ghost of a fallen elf.</description>
		<attributes>
			<atk value="168"/>
			<def value="21"/>
			<hp value="121"/>
			<speed value="0.4"/>
			<size value="1,1"/>
		</attributes>
		<level value="28"/>
		<experience value="1020"/>
		<respawn value="1500"/>
		<corpse name="puddle_green"/>
		<drops>
			<item value="money" quantity="[3,30]" probability="90.0"/>
			<item value="antidote" quantity="[1,1]" probability="60.0"/>
			<item value="blood chain armor" quantity="[1,1]" probability="1.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>
	
	<creature name="infernal demon ghost">
		<type class="faumonia_duchy" subclass="demon_ghost" tileid="faumonia_duchy.png:2"/>
		<description>You see the tormented ghost of an infernal demon.</description>
		<attributes>
			<atk value="181"/>
			<def value="21"/>
			<hp value="161"/>
			<speed value="0.4"/>
			<size value="1,1"/>
		</attributes>
		<level value="29"/>
		<experience value="1060"/>
		<respawn value="1500"/>
		<corpse name="puddle_light_blue"/>
		<drops>
			<item value="money" quantity="[3,30]" probability="90.0"/>
			<item value="antidote" quantity="[1,1]" probability="60.0"/>
			<item value="blood robe" quantity="[1,1]" probability="1.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>
	
	<creature name="imperial ghost archer">
		<type class="faumonia_duchy" subclass="ghost_archer" tileid="faumonia_duchy.png:3"/>
		<description>You see the ghostly spirit of an imperial archer still drawing his bow.</description>
		<attributes>
			<atk value="181"/>
			<def value="8"/>
			<hp value="180"/>
			<speed value="0.6"/>
			<size value="1,1"/>
		</attributes>
		<level value="31"/>
		<experience value="1140"/>
		<respawn value="1500"/>
		<corpse name="puddle_brown"/>
		<drops>
			<item value="money" quantity="[1,17]" probability="100.0"/>
			<item value="antidote" quantity="[1,1]" probability="60.0"/>
			<item value="blood chain armor" quantity="[1,1]" probability="1.0"/>
			<item value="wooden arrow" quantity="[1,14]" probability="10.0"/>
		</drops>
		<equips>
			<slot name="lhand" item="wooden arrow" quantity="10000"/>
			<slot name="rhand" item="wooden bow" quantity="1"/>
		</equips>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="archer"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="spiteful ghost archer">
		<type class="faumonia_duchy" subclass="spiteful_ghost_archer" tileid="faumonia_duchy.png:4"/>
		<description>You see a vengeful ghost archer seeking retribution.</description>
		<attributes>
			<atk value="162"/>
			<def value="7"/>
			<hp value="235"/>
			<speed value="0.6"/>
			<size value="1,1"/>
		</attributes>
		<level value="34"/>
		<experience value="1180"/>
		<respawn value="1500"/>
		<corpse name="puddle_brown"/>
		<drops>
			<item value="money" quantity="[1,17]" probability="100.0"/>
			<item value="antidote" quantity="[1,1]" probability="60.0"/>
			<item value="blood leather legs" quantity="[1,1]" probability="1.0"/>
			<item value="blood robe" quantity="[1,1]" probability="1.0"/>
			<item value="wooden arrow" quantity="[1,14]" probability="70.0"/>
		</drops>
		<equips>
			<slot name="lhand" item="wooden arrow" quantity="10000"/>
			<slot name="rhand" item="wooden bow" quantity="1"/>
		</equips>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="archer"/>
			<profile name="patrolling"/>
		</ai>
	</creature>
	
	<creature name="giant phantom">
	    <type class="faumonia_duchy" subclass="giant_ghost" tileid="faumonia_duchy.png:5"/>
		<description>You see a towering giant phantom looming silently.</description>
		<attributes>
			<atk value="187"/>
			<def value="33"/>
			<hp value="1200"/>
			<speed value="0.5"/>
			<size value="2,2"/>
		</attributes>
		<level value="40"/>
		<experience value="6400"/>
		<respawn value="7400"/>
		<corpse name="puddle_big"/>
		<drops>
			<item value="greater antidote" quantity="[1,6]" probability="60.0"/>
			<item value="money" quantity="[30,150]" probability="100.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<profile name="brave"/>
			<profile name="animal"/>
			<profile name="offensive"/>
			<profile name="patrolling"/>
		</ai>
	</creature>
	
</creatures>

=== marcospdsf/EOT/data/conf/creatures/troll.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../creatures.xsd">

  <!-- START: cyclops -->

  <creature name="cyclops">
    <type class="giant" subclass="cyclops" tileid="troll.png:3"/>
    <description>You see a cyclops. It just has one eye.</description>
    <attributes>
      <atk value="125"/>
      <def value="26"/>
      <hp value="60"/>
      <speed value="0.5"/>
      <size value="1,1"/>
    </attributes>
    <level value="9"/>
    <experience value="90"/>
    <respawn value="1200"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="chain armor" quantity="[1,1]" probability="1.0"/>
      <item value="leather cuirass" quantity="[1,1]" probability="10.0"/>
      <item value="studded boots" quantity="[1,1]" probability="0.5"/>
      <item value="enhanced mace" quantity="[1,1]" probability="1.0"/>
      <item value="studded shield" quantity="[1,1]" probability="0.5"/>
      <!--<item value="tripe" quantity="[1,2]" probability="50.0"/>-->
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <sound value="cyclops-scream-01"/>
        <sound value="cyclops-yell-01"/>
        <sound value="cyclops-laugh-01"/>
        <sound value="cyclops-laugh-02"/>
        <sound value="cyclops-grunt-01"/>
      </says>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <!-- END: cyclops -->

  <!-- START: troll -->

  <creature name="troll">
    <type class="troll" subclass="troll" tileid="troll.png:0"/>
    <description>You see a troll, be careful in his terrain.</description>
    <attributes>
      <atk value="135"/>
      <def value="34"/>
      <hp value="60"/>
      <speed value="0.5"/>
      <size value="1,1"/>
    </attributes>
    <level value="10"/>
    <experience value="110"/>
    <respawn value="1210"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="chain armor" quantity="[1,1]" probability="3.0"/>
      <item value="chain legs" quantity="[1,1]" probability="2.0"/>
      <item value="enhanced chainmail" quantity="[1,1]" probability="0.05"/>
      <item value="flail" quantity="[1,1]" probability="30.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <sound value="troll-growl-01"/>
        <sound value="troll-growl-02"/>
        <sound value="troll-growl-03"/>
        <sound value="troll-growl-04"/>
      </says>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <creature name="red troll">
    <type class="troll" subclass="red_troll" tileid="troll.png:2"/>
    <description>You see a red troll, he's burning with anger.</description>
    <attributes>
      <atk value="190"/>
      <def value="34"/>
      <hp value="110"/>
      <speed value="0.7"/>
      <size value="1,1"/>
    </attributes>
    <level value="16"/>
    <experience value="200"/>
    <respawn value="1230"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="scale armor" quantity="[1,1]" probability="3.0"/>
      <item value="chain legs" quantity="[1,1]" probability="4.0"/>
      <item value="flail" quantity="[1,1]" probability="30.0"/>
      <item value="ugmash" quantity="[1,1]" probability="1.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <sound value="troll-growl-01"/>
        <sound value="troll-growl-02"/>
        <sound value="troll-growl-03"/>
        <sound value="troll-growl-04"/>
      </says>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <creature name="cave troll">
    <type class="troll" subclass="cave_troll" tileid="troll.png:1"/>
    <description></description>
    <attributes>
      <atk value="474"/>
      <def value="45"/>
      <hp value="1000"/>
      <speed value="0.7"/>
      <size value="2,2"/>
    </attributes>
    <level value="63"/>
    <experience value="3100"/>
    <respawn value="1870"/>
    <corpse name="humanoid_2x2"/>
    <drops>
      <item value="meat" quantity="[1,5]" probability="10.5"/>
      <!--<item value="tripe" quantity="[1,2]" probability="50.0"/>-->
      <item value="ugmash" quantity="[1,1]" probability="1.0"/>
      <item value="barbarian armor" quantity="[1,1]" probability="5.5"/>
      <item value="stone boots" quantity="[1,1]" probability="2.5"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <noise state="idle follow fight" value="Uggga yggga arghhhhh"/>
        <noise state="idle follow fight" value="Ooggga UGGga arhhh"/>
        <sound value="growl-large-3"/>
        <sound value="grunt-large-1"/>
        <sound value="grunt-large-2"/>
      </says>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <!-- END: troll -->

</creatures>

=== marcospdsf/EOT/data/conf/creatures/pol_kamienne.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../creatures.xsd ">

	<!-- START: kamienne -->

	<creature name="animated stone">
		<type class="pol/kamienne" subclass="kamien" tileid="pol_kamienne.png:0"/>
		<description>You see a small animated stone shifting across the dirt.</description>
		<attributes>
			<atk value="97"/>
			<def value="97"/>
			<hp value="12"/>
			<speed value="0.3"/>
			<size value="1,1"/>
		</attributes>
		<level value="20"/>
		<experience value="280"/>
		<respawn value="9600"/>
		<corpse name="rocks"/>
		<drops>
			<item value="stone boots" quantity="[1,1]" probability="0.0001"/>
			<item value="stone armor" quantity="[1,1]" probability="0.0001"/>
			<item value="stone shield" quantity="[1,1]" probability="0.5"/>
		</drops>
		<equips/>
		<ai>
			<says>
				<sound value="pol-stones2"/>
			</says>
			<profile name="brave"/>
			<profile name="animal"/>
			<profile name="offensive"/>
		</ai>
	</creature>

	<creature name="stone spire">
		<type class="pol/kamienne" subclass="wieza" tileid="pol_kamienne.png:1"/>
		<description>You see a walking stone spire towering in the distance.</description>
		<attributes>
			<atk value="750"/>
			<def value="375"/>
			<hp value="10285"/>
			<speed value="0.2"/>
			<size value="2,2"/>
		</attributes>
		<level value="200"/>
		<experience value="10920"/>
		<respawn value="13449"/>
		<corpse name="giant_rocks"/>
		<drops>
			<item value="stone boots" quantity="[1,1]" probability="5.0"/>
			<item value="stone armor" quantity="[1,1]" probability="2.0"/>
			<item value="stone shield" quantity="[1,1]" probability="5.0"/>
			<item value="stone cloak" quantity="[1,1]" probability="1.0"/>
		</drops>
		<equips/>
		<ai>
			<says>
				<sound value="pol-giant"/>
			</says>
			<profile name="brave"/>
			<profile name="animal"/>
			<profile name="offensive"/>
			<profile name="rare"/>
		</ai>
	</creature>

	<!-- END: kamienne -->

</creatures>

=== marcospdsf/EOT/data/conf/creatures/slime.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../creatures.xsd">

  <creature name="black slime">
    <type class="slime" subclass="black_slime" tileid="slime.png:2"/>
    <description>You see a black slime, with a sticky trail behind it.</description>
    <attributes>
      <atk value="250"/>
      <def value="36"/>
      <hp value="210"/>
      <speed value="0.5"/>
      <size value="1,1"/>
    </attributes>
    <level value="24"/>
    <experience value="370"/>
    <respawn value="1290"/>
    <corpse name="puddle_black" harmless="puddle_black"/>
    <drops>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <movement value="loop-drag-slimy-1"/>
      </says>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <creature name="brown slime">
    <type class="slime" subclass="brown_slime" tileid="slime.png:1"/>
    <description>You see a brown slime, sticky and hungry.</description>
    <attributes>
      <atk value="184"/>
      <def value="26"/>
      <hp value="160"/>
      <speed value="0.4"/>
      <size value="1,1"/>
    </attributes>
    <level value="16"/>
    <experience value="200"/>
    <respawn value="1230"/>
    <corpse name="puddle_brown" harmless="puddle_brown"/>
    <drops>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <movement value="loop-drag-slimy-1"/>
      </says>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <creature name="green slime">
    <type class="slime" subclass="green_slime" tileid="slime.png:0"/>
    <description>You see a green slime, sticky and shiny.</description>
    <attributes>
      <atk value="114"/>
      <def value="18"/>
      <hp value="90"/>
      <speed value="0.3"/>
      <size value="1,1"/>
    </attributes>
    <level value="8"/>
    <experience value="80"/>
    <respawn value="1200"/>
    <corpse name="puddle_green" harmless="puddle_green"/>
    <drops>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <movement value="loop-drag-slimy-1"/>
      </says>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <creature name="twilight slime">
    <type class="slime" subclass="twilight_slime" tileid="animal.png:-1"/>
    <description>You see a twilight slime, so strange and beautiful. Why is it coming towards you? Runnnnnnnnn!</description>
    <attributes>
      <atk value="718"/>
      <def value="88"/>
      <hp value="1290"/>
      <speed value="0.5"/>
      <size value="1,1"/>
    </attributes>
    <level value="111"/>
    <experience value="14580"/>
    <respawn value="1200"/>
    <corpse name="puddle_light_blue" harmless="puddle_light_blue"/>
    <drops>
      <item value="greater antidote" quantity="[1,1]" probability="100.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <movement value="loop-drag-slimy-1"/>
      </says>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="patrolling"/>
      <profile name="abnormal"/>
    </ai>
  </creature>

</creatures>
