=== marcospdsf/EOT/data/conf/creatures.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
		targetNamespace="stendhal" xmlns:tns="http://www.example.org/creatures"
		elementFormDefault="qualified" xmlns:Q2="stendhal">

	<xsd:element name="creatures" type="Q2:CreaturesType"></xsd:element>

	<xsd:complexType name="CreaturesType">
		<xsd:sequence>
			<xsd:element name="creature" type="Q2:CreatureType"
				minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="CreatureType">
		<xsd:sequence>
			<xsd:element name="type" type="Q2:Type" minOccurs="1"/>
			<xsd:element name="hidden" type="xsd:string" minOccurs="0"/>
			<xsd:element name="description" type="xsd:string" minOccurs="0"/>
			<xsd:element name="attributes" type="Q2:Attributes" minOccurs="1"/>
			<xsd:element name="level" type="Q2:Level" minOccurs="1"/>
			<xsd:element name="experience" type="Q2:Experience" minOccurs="1"/>
			<xsd:element name="respawn" type="Q2:Respawn"/>
			<xsd:element name="blood" type="Q2:Blood" minOccurs="0"/>
			<xsd:element name="corpse" type="Q2:Corpse"/>
			<xsd:element name="drops" type="Q2:Drops" minOccurs="0"/>
			<xsd:element name="slots" type="Q2:Slots" minOccurs="0"/>
			<xsd:element name="equips" type="Q2:Equips" minOccurs="0"/>
			<xsd:element name="abilities" type="Q2:Abilities" minOccurs="0"/>
			<xsd:element name="ai" type="Q2:Ai" minOccurs="1"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string"/>
		<xsd:attribute name="condition" type="xsd:string" use="optional"/>
	</xsd:complexType>

	<xsd:complexType name="Item">
		<xsd:attribute name="value" type="xsd:string"/>
		<xsd:attribute name="quantity" type="xsd:string"/>
		<xsd:attribute name="probability" type="xsd:double"/>
	</xsd:complexType>

	<xsd:complexType name="SpecialItem">
		<xsd:attribute name="value" type="xsd:string" use="required"/>
		<xsd:attribute name="note" type="xsd:string" use="optional"/>
	</xsd:complexType>

	<xsd:complexType name="Drops">
		<xsd:sequence>
			<xsd:element name="item" type="Q2:Item" minOccurs="0"
				maxOccurs="unbounded"/>
			<xsd:element name="special" type="Q2:SpecialItem" minOccurs="0"
				maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Respawn">
		<xsd:sequence>
		</xsd:sequence>
		<xsd:attribute name="value" type="xsd:positiveInteger"/>
	</xsd:complexType>

	<xsd:complexType name="Blood">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="Corpse">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="width" type="xsd:positiveInteger"/>
		<xsd:attribute name="height" type="xsd:positiveInteger"/>
		<xsd:attribute name="harmless" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Attributes">
		<xsd:sequence>
			<xsd:element name="atk" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="ratk" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="def" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="hp" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="speed" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:decimal"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="size" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="noise" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="state" type="xsd:string"/>
					<xsd:attribute name="value" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="resistance" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="visibility" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Ai">
		<xsd:sequence>
			<xsd:element name="says" type="Q2:Says" minOccurs="0"/>
			<xsd:element name="profile" type="Q2:Profile" minOccurs="1"
				maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Says">
		<xsd:sequence>
			<xsd:element name="noise" type="Q2:Text" minOccurs="0"
				maxOccurs="unbounded"/>
			<xsd:element name="text" type="Q2:Text" minOccurs="0"
				maxOccurs="unbounded"/>
			<xsd:element name="sound" type="Q2:Sound" minOccurs="0"
				maxOccurs="unbounded"/>
			<xsd:element name="movement" type="Q2:Movement" minOccurs="0"
				maxOccurs="unbounded"/>
			<xsd:element name="death" type="Q2:Death" minOccurs="0"
				maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Text">
		<xsd:attribute name="value" type="xsd:string"/>
		<xsd:attribute name="state" type="xsd:string"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="Sound">
		<xsd:attribute name="value" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Movement">
		<xsd:attribute name="value" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Death">
		<xsd:attribute name="value" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Profile">
		<xsd:attribute name="name" type="xsd:string"/>
		<xsd:attribute name="params" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Type">
		<xsd:attribute name="class" type="xsd:string"/>
		<xsd:attribute name="subclass" type="xsd:string"/>
		<xsd:attribute name="shadow" type="xsd:string"/>
		<xsd:attribute name="tileid" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Level">
		<xsd:attribute name="value" type="xsd:integer"/>
	</xsd:complexType>

	<xsd:complexType name="Experience">
		<xsd:attribute name="value" type="xsd:integer"/>
	</xsd:complexType>

	<xsd:complexType name="Slots">
		<xsd:sequence>
			<xsd:element name="slot" type="xsd:string" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Equips">
		<xsd:sequence>
			<xsd:element name="slot" type="Q2:Slot" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Abilities">
		<xsd:sequence>
			<xsd:element name="damage" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="type" type="xsd:string" default="cut"/>
					<xsd:attribute name="rangedType" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="susceptibility" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:attribute name="type" type="xsd:string"/>
					<xsd:attribute name="value" type="xsd:decimal"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="statusattack" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:attribute name="type" type="xsd:string"/>
					<xsd:attribute name="value" type="xsd:decimal"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Slot">
		<xsd:sequence>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="item" type="xsd:string" use="required"/>
		<xsd:attribute name="quantity" type="xsd:positiveInteger"/>
	</xsd:complexType>

</xsd:schema>

=== marcospdsf/EOT/data/conf/creatures/pol_wilkolaki.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../creatures.xsd ">

	<!-- START: wilkolaki -->

	<creature name="werewolf sellsword">
		<type class="pol/wilkolaki" subclass="wilkolak_zoldak" tileid="pol_wilkolaki.png:0"/>
		<description>You see a mercenary werewolf prowling under the full moon.</description>
		<attributes>
			<atk value="1250"/>
			<def value="149"/>
			<hp value="1290"/>
			<speed value="0.8"/>
			<size value="1,1"/>
		</attributes>
		<level value="159"/>
		<experience value="9110"/>
		<respawn value="5110"/>
		<corpse name="animal"/>
		<drops>
			<item value="money" quantity="[29,129]" probability="100.0"/>
			<item value="green dragon cloak" quantity="[1,1]" probability="10.0"/>
			<item value="emerald" quantity="[1,1]" probability="1.0"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
			<profile name="heal" params="5,50"/>
		</ai>
	</creature>

	<creature name="werewolf warrior">
		<type class="pol/wilkolaki" subclass="wilkolak_wojak" tileid="pol_wilkolaki.png:1"/>
		<description>You see a ferocious werewolf warrior thirsting for battle.</description>
		<attributes>
			<atk value="1450"/>
			<def value="169"/>
			<hp value="1590"/>
			<speed value="0.9"/>
			<size value="1,1"/>
		</attributes>
		<level value="161"/>
		<experience value="9310"/>
		<respawn value="7510"/>
		<corpse name="animal"/>
		<drops>
			<item value="money" quantity="[29,129]" probability="100.0"/>
			<item value="green dragon cloak" quantity="[1,1]" probability="20.0"/>
			<item value="emerald" quantity="[1,1]" probability="10.0"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
			<profile name="heal" params="5,50"/>
		</ai>
	</creature>

	<creature name="werewolf archer">
		<type class="pol/wilkolaki" subclass="wilkolak_lucznik" tileid="pol_wilkolaki.png:2"/>
		<description>You see a werewolf archer stalking prey from the treetops.</description>
		<attributes>
			<atk value="1950"/>
			<def value="109"/>
			<hp value="790"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="151"/>
		<experience value="8310"/>
		<respawn value="3510"/>
		<corpse name="animal"/>
		<drops>
			<item value="money" quantity="[129,329]" probability="90.0"/>
			<item value="green dragon cloak" quantity="[1,1]" probability="25.0"/>
			<item value="emerald" quantity="[1,1]" probability="15.0"/>
			<item value="longbow" quantity="[1,1]" probability="7.5"/>
		</drops>
		<equips>
			<slot name="lhand" item="wooden arrow" quantity="10000"/>
			<slot name="rhand" item="longbow" quantity="1"/>
		</equips>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="archer"/>
			<profile name="patrolling"/>
			<profile name="heal" params="5,50"/>
		</ai>
	</creature>

	<creature name="werewolf guardian">
		<type class="pol/wilkolaki" subclass="wilkolak_lider" tileid="pol_wilkolaki.png:3"/>
		<description>You see an armored werewolf guardian defending the pack.</description>
		<attributes>
			<atk value="1150"/>
			<def value="769"/>
			<hp value="1790"/>
			<speed value="0.7"/>
			<size value="1,1"/>
		</attributes>
		<level value="141"/>
		<experience value="7310"/>
		<respawn value="3510"/>
		<corpse name="animal"/>
		<drops>
			<item value="money" quantity="[29,129]" probability="100.0"/>
			<item value="green dragon cloak" quantity="[1,1]" probability="10.0"/>
			<item value="emerald" quantity="[1,1]" probability="1.0"/>
			<item value="green dragon shield" quantity="[1,1]" probability="2.5"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
			<profile name="heal" params="5,50"/>
		</ai>
	</creature>

	<creature name="werewolf stalker">
		<type class="pol/wilkolaki" subclass="wilkolak_zwiadowca" tileid="pol_wilkolaki.png:4"/>
		<description>You see a swift werewolf stalker tracking your scent.</description>
		<attributes>
			<atk value="1750"/>
			<def value="269"/>
			<hp value="1990"/>
			<speed value="0.9"/>
			<size value="1,1"/>
		</attributes>
		<level value="171"/>
		<experience value="9910"/>
		<respawn value="3510"/>
		<corpse name="animal"/>
		<drops>
			<item value="money" quantity="[29,129]" probability="100.0"/>
			<item value="green dragon cloak" quantity="[1,1]" probability="10.0"/>
			<item value="emerald" quantity="[1,1]" probability="1.0"/>
			<item value="dagger" quantity="[1,1]" probability="22.5"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
			<profile name="heal" params="5,50"/>
		</ai>
	</creature>

	<creature name="werewolf shaman">
		<type class="pol/wilkolaki" subclass="wilkolak_szaman" tileid="pol_wilkolaki.png:5"/>
		<description>You see a mystical werewolf shaman channeling primal blood magic.</description>
		<attributes>
			<atk value="1750"/>
			<def value="269"/>
			<hp value="1990"/>
			<speed value="0.9"/>
			<size value="1,1"/>
		</attributes>
		<level value="171"/>
		<experience value="9910"/>
		<respawn value="3510"/>
		<corpse name="animal"/>
		<drops>
			<item value="money" quantity="[9,29]" probability="100.0"/>
			<item value="black dragon cloak" quantity="[1,1]" probability="5.0"/>
			<item value="emerald" quantity="[1,1]" probability="1.0"/>
			<item value="greater antidote" quantity="[1,2]" probability="20.0"/>
		</drops>
		<equips>
			<slot name="lhand" item="wooden arrow" quantity="10000"/>
			<slot name="rhand" item="longbow" quantity="1"/>
		</equips>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="heal" params="10,60"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="werewolf princess">
		<type class="pol/wilkolaki" subclass="wilkolak_ksiezniczka" tileid="pol_wilkolaki.png:6"/>
		<description>You see the royal werewolf princess commanding her pack.</description>
		<attributes>
			<atk value="2150"/>
			<def value="369"/>
			<hp value="2990"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="191"/>
		<experience value="9910"/>
		<respawn value="3510"/>
		<corpse name="animal"/>
		<drops>
			<item value="money" quantity="[9,329]" probability="100.0"/>
			<item value="blue striped cloak" quantity="[1,1]" probability="15.0"/>
			<item value="sapphire" quantity="[1,1]" probability="31.0"/>
			<item value="pelt" quantity="[1,1]" probability="50.0"/>
			<item value="greater antidote" quantity="[1,2]" probability="20.0"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="heal" params="10,60"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="werewolf prince">
		<type class="pol/wilkolaki" subclass="wilkolak_ksiaze" tileid="pol_wilkolaki.png:7"/>
		<description>You see the fearsome werewolf prince ruling the mountain wilderness.</description>
		<attributes>
			<atk value="2350"/>
			<def value="469"/>
			<hp value="2990"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="199"/>
		<experience value="9910"/>
		<respawn value="9510"/>
		<corpse name="animal"/>
		<drops>
			<item value="money" quantity="[9,329]" probability="100.0"/>
			<item value="sapphire" quantity="[1,1]" probability="11.0"/>
			<item value="golden blade" quantity="[1,1]" probability="0.05"/>
			<item value="greater antidote" quantity="[1,7]" probability="17.0"/>
			<item value="chaos cloak" quantity="[1,1]" probability="0.25"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="heal" params="10,60"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<!-- END: wilkolaki -->

</creatures>

=== marcospdsf/EOT/data/conf/creatures/pol_pokutniki.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../creatures.xsd ">

	<!-- START: pokutniki -->

	<creature name="marsh penitent">
		<type class="pol/pokutniki" subclass="pit_pokutnik_bronz" tileid="pol_pokutniki.png:0"/>
		<description>You see a sorrowful marsh penitent seeking redemption.</description>
		<attributes>
			<atk value="400"/>
			<def value="33"/>
			<hp value="2900"/>
			<speed value="1.0"/>
			<size value="2,2"/>
		</attributes>
		<level value="120"/>
		<experience value="21321"/>
		<respawn value="10101"/>
		<corpse name="giant_knight"/>
		<drops>
			<item value="greater potion" quantity="[1,2]" probability="80.0"/>
			<item value="money" quantity="[30,200]" probability="100.0"/>
			<item value="red gloves" quantity="[1,1]" probability="2.5"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="animal"/>
			<profile name="offensive"/>
			<profile name="heal" params="5,25"/>
			<profile name="attack weakest"/>
		</ai>
	</creature>

	<creature name="moorland penitent">
		<type class="pol/pokutniki" subclass="pit_pokutnik_fiolet" tileid="pol_pokutniki.png:1"/>
		<description>You see a burdened moorland penitent wandering the heather.</description>
		<attributes>
			<atk value="410"/>
			<def value="34"/>
			<hp value="3000"/>
			<speed value="1.0"/>
			<size value="2,2"/>
		</attributes>
		<level value="125"/>
		<experience value="22321"/>
		<respawn value="10101"/>
		<corpse name="giant_knight"/>
		<drops>
			<item value="greater potion" quantity="[1,2]" probability="80.0"/>
			<item value="money" quantity="[30,200]" probability="100.0"/>
			<item value="shadow gloves" quantity="[1,1]" probability="0.5"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="animal"/>
			<profile name="offensive"/>
			<profile name="heal" params="5,25"/>
			<profile name="attack weakest"/>
		</ai>
	</creature>

	<creature name="night penitent">
		<type class="pol/pokutniki" subclass="pit_pokutnik_granat" tileid="pol_pokutniki.png:2"/>
		<description>You see a dark night penitent shrouded in remorse.</description>
		<attributes>
			<atk value="420"/>
			<def value="35"/>
			<hp value="3100"/>
			<speed value="1.0"/>
			<size value="2,2"/>
		</attributes>
		<level value="130"/>
		<experience value="23321"/>
		<respawn value="10101"/>
		<corpse name="giant_knight"/>
		<drops>
			<item value="greater potion" quantity="[1,2]" probability="80.0"/>
			<item value="money" quantity="[30,200]" probability="100.0"/>
			<item value="blue gloves" quantity="[1,1]" probability="2.5"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="animal"/>
			<profile name="offensive"/>
			<profile name="heal" params="5,25"/>
			<profile name="attack weakest"/>
		</ai>
	</creature>

	<creature name="dusk penitent">
		<type class="pol/pokutniki" subclass="pit_pokutnik_szary" tileid="pol_pokutniki.png:3"/>
		<description>You see an ashen dusk penitent lingering in twilight.</description>
		<attributes>
			<atk value="430"/>
			<def value="36"/>
			<hp value="3200"/>
			<speed value="1.0"/>
			<size value="2,2"/>
		</attributes>
		<level value="135"/>
		<experience value="24321"/>
		<respawn value="10101"/>
		<corpse name="giant_knight"/>
		<drops>
			<item value="greater potion" quantity="[1,2]" probability="80.0"/>
			<item value="money" quantity="[30,200]" probability="100.0"/>
			<item value="ice gloves" quantity="[1,1]" probability="0.5"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="animal"/>
			<profile name="offensive"/>
			<profile name="heal" params="5,25"/>
			<profile name="attack weakest"/>
		</ai>
	</creature>

	<creature name="meadow penitent">
		<type class="pol/pokutniki" subclass="pit_pokutnik_zielen" tileid="pol_pokutniki.png:4"/>
		<description>You see a green meadow penitent burdened with eternal grief.</description>
		<attributes>
			<atk value="450"/>
			<def value="37"/>
			<hp value="3300"/>
			<speed value="1.0"/>
			<size value="2,2"/>
		</attributes>
		<level value="150"/>
		<experience value="25321"/>
		<respawn value="10101"/>
		<corpse name="giant_knight"/>
		<drops>
			<item value="greater potion" quantity="[1,2]" probability="80.0"/>
			<item value="money" quantity="[30,200]" probability="100.0"/>
			<item value="elvish shield" quantity="[1,1]" probability="12.5"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="animal"/>
			<profile name="offensive"/>
			<profile name="heal" params="5,25"/>
			<profile name="attack weakest"/>
		</ai>
	</creature>

	<!-- END: pokutniki -->

</creatures>

=== marcospdsf/EOT/data/conf/creatures/faumonia_kamienie.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../creatures.xsd ">

	<creature name="strange pebble man">
		<type class="faumonia_kamienie" subclass="dziwny_czlek" tileid="faumonia_kamyki.png:0"/>
		<description>You see a strange little stone fellow.</description>
		<attributes>
			<atk value="10"/>
			<def value="1"/>
			<hp value="100"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="5"/>
		<experience value="100"/>
		<respawn value="10000"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="antidote" quantity="[1,3]" probability="99.9"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<profile name="human"/>
		</ai>
	</creature>
	
	<creature name="strange stone creature">
		<type class="faumonia_kamienie" subclass="dziwny_czlek_2" tileid="faumonia_kamyki.png:1"/>
		<description>You see a strange stone creature wandering around.</description>
		<attributes>
			<atk value="50"/>
			<def value="5"/>
			<hp value="2000"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="40"/>
		<experience value="1000"/>
		<respawn value="15000"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="greater antidote" quantity="[1,3]" probability="99.9"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<profile name="human"/>
		</ai>
	</creature>
	
	<creature name="strange stone humanoid">
		<type class="faumonia_kamienie" subclass="dziwny_czlek_3" tileid="faumonia_kamyki.png:2"/>
		<description>You see a strange stone humanoid standing motionless.</description>
		<attributes>
			<atk value="500"/>
			<def value="50"/>
			<hp value="10000"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="250"/>
		<experience value="10000"/>
		<respawn value="20000"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="greater potion" quantity="[1,3]" probability="99.9"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<profile name="human"/>
		</ai>
	</creature>
	
</creatures>
