=== marcospdsf/EOT/data/conf/creatures.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
		targetNamespace="stendhal" xmlns:tns="http://www.example.org/creatures"
		elementFormDefault="qualified" xmlns:Q2="stendhal">

	<xsd:element name="creatures" type="Q2:CreaturesType"></xsd:element>

	<xsd:complexType name="CreaturesType">
		<xsd:sequence>
			<xsd:element name="creature" type="Q2:CreatureType"
				minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="CreatureType">
		<xsd:sequence>
			<xsd:element name="type" type="Q2:Type" minOccurs="1"/>
			<xsd:element name="hidden" type="xsd:string" minOccurs="0"/>
			<xsd:element name="description" type="xsd:string" minOccurs="0"/>
			<xsd:element name="attributes" type="Q2:Attributes" minOccurs="1"/>
			<xsd:element name="level" type="Q2:Level" minOccurs="1"/>
			<xsd:element name="experience" type="Q2:Experience" minOccurs="1"/>
			<xsd:element name="respawn" type="Q2:Respawn"/>
			<xsd:element name="blood" type="Q2:Blood" minOccurs="0"/>
			<xsd:element name="corpse" type="Q2:Corpse"/>
			<xsd:element name="drops" type="Q2:Drops" minOccurs="0"/>
			<xsd:element name="slots" type="Q2:Slots" minOccurs="0"/>
			<xsd:element name="equips" type="Q2:Equips" minOccurs="0"/>
			<xsd:element name="abilities" type="Q2:Abilities" minOccurs="0"/>
			<xsd:element name="ai" type="Q2:Ai" minOccurs="1"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string"/>
		<xsd:attribute name="condition" type="xsd:string" use="optional"/>
	</xsd:complexType>

	<xsd:complexType name="Item">
		<xsd:attribute name="value" type="xsd:string"/>
		<xsd:attribute name="quantity" type="xsd:string"/>
		<xsd:attribute name="probability" type="xsd:double"/>
	</xsd:complexType>

	<xsd:complexType name="SpecialItem">
		<xsd:attribute name="value" type="xsd:string" use="required"/>
		<xsd:attribute name="note" type="xsd:string" use="optional"/>
	</xsd:complexType>

	<xsd:complexType name="Drops">
		<xsd:sequence>
			<xsd:element name="item" type="Q2:Item" minOccurs="0"
				maxOccurs="unbounded"/>
			<xsd:element name="special" type="Q2:SpecialItem" minOccurs="0"
				maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Respawn">
		<xsd:sequence>
		</xsd:sequence>
		<xsd:attribute name="value" type="xsd:positiveInteger"/>
	</xsd:complexType>

	<xsd:complexType name="Blood">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="Corpse">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="width" type="xsd:positiveInteger"/>
		<xsd:attribute name="height" type="xsd:positiveInteger"/>
		<xsd:attribute name="harmless" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Attributes">
		<xsd:sequence>
			<xsd:element name="atk" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="ratk" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="def" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="hp" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="speed" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:decimal"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="size" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="noise" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="state" type="xsd:string"/>
					<xsd:attribute name="value" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="resistance" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="visibility" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Ai">
		<xsd:sequence>
			<xsd:element name="says" type="Q2:Says" minOccurs="0"/>
			<xsd:element name="profile" type="Q2:Profile" minOccurs="1"
				maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Says">
		<xsd:sequence>
			<xsd:element name="noise" type="Q2:Text" minOccurs="0"
				maxOccurs="unbounded"/>
			<xsd:element name="text" type="Q2:Text" minOccurs="0"
				maxOccurs="unbounded"/>
			<xsd:element name="sound" type="Q2:Sound" minOccurs="0"
				maxOccurs="unbounded"/>
			<xsd:element name="movement" type="Q2:Movement" minOccurs="0"
				maxOccurs="unbounded"/>
			<xsd:element name="death" type="Q2:Death" minOccurs="0"
				maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Text">
		<xsd:attribute name="value" type="xsd:string"/>
		<xsd:attribute name="state" type="xsd:string"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="Sound">
		<xsd:attribute name="value" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Movement">
		<xsd:attribute name="value" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Death">
		<xsd:attribute name="value" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Profile">
		<xsd:attribute name="name" type="xsd:string"/>
		<xsd:attribute name="params" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Type">
		<xsd:attribute name="class" type="xsd:string"/>
		<xsd:attribute name="subclass" type="xsd:string"/>
		<xsd:attribute name="shadow" type="xsd:string"/>
		<xsd:attribute name="tileid" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Level">
		<xsd:attribute name="value" type="xsd:integer"/>
	</xsd:complexType>

	<xsd:complexType name="Experience">
		<xsd:attribute name="value" type="xsd:integer"/>
	</xsd:complexType>

	<xsd:complexType name="Slots">
		<xsd:sequence>
			<xsd:element name="slot" type="xsd:string" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Equips">
		<xsd:sequence>
			<xsd:element name="slot" type="Q2:Slot" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Abilities">
		<xsd:sequence>
			<xsd:element name="damage" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="type" type="xsd:string" default="cut"/>
					<xsd:attribute name="rangedType" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="susceptibility" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:attribute name="type" type="xsd:string"/>
					<xsd:attribute name="value" type="xsd:decimal"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="statusattack" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:attribute name="type" type="xsd:string"/>
					<xsd:attribute name="value" type="xsd:decimal"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Slot">
		<xsd:sequence>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="item" type="xsd:string" use="required"/>
		<xsd:attribute name="quantity" type="xsd:positiveInteger"/>
	</xsd:complexType>

</xsd:schema>

=== marcospdsf/EOT/data/conf/creatures/pol_elfy_gorskie.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../creatures.xsd ">

	<!-- START: elf gorski -->

	<creature name="mountain elf page">
		<type class="pol/elfy_gorskie" subclass="ae_elf_gorski_maskotka" tileid="pol_elfy_gorskie.png:0"/>
		<description>You see a young mountain elf page clutching a toy.</description>
		<attributes>
			<atk value="180"/>
			<def value="17"/>
			<hp value="120"/>
			<speed value="0.9"/>
			<size value="1,1"/>
		</attributes>
		<level value="35"/>
		<experience value="1210"/>
		<respawn value="1110"/>
		<corpse name="human"/>
		<drops>
			<item value="teddy" quantity="[1,1]" probability="1.0"/>
		</drops>
		<equips/>
		<ai>
			<profile name="coward"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="mountain elf handmaiden">
		<type class="pol/elfy_gorskie" subclass="ae_elf_gorski_sluzka" tileid="pol_elfy_gorskie.png:1"/>
		<description>You see a gentle mountain elf handmaiden attending to court.</description>
		<attributes>
			<atk value="191"/>
			<def value="24"/>
			<hp value="150"/>
			<speed value="0.9"/>
			<size value="1,1"/>
		</attributes>
		<level value="37"/>
		<experience value="1310"/>
		<respawn value="1310"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[1,159]" probability="19.0"/>
			<item value="cloth" quantity="[1,1]" probability="1.0"/>
		</drops>
		<equips/>
		<ai>
			<profile name="coward"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="mountain elf noblewoman">
		<type class="pol/elfy_gorskie" subclass="ae_elf_gorski_dama" tileid="pol_elfy_gorskie.png:7"/>
		<description>You see an elegant mountain elf noblewoman in ornate robes.</description>
		<attributes>
			<atk value="193"/>
			<def value="26"/>
			<hp value="155"/>
			<speed value="0.8"/>
			<size value="1,1"/>
		</attributes>
		<level value="38"/>
		<experience value="1410"/>
		<respawn value="1510"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[29,59]" probability="25.0"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="mountain elf sentry">
		<type class="pol/elfy_gorskie" subclass="ae_elf_gorski_strazniczka" tileid="pol_elfy_gorskie.png:9"/>
		<description>You see a vigilant mountain elf sentry guarding the mountain redoubt.</description>
		<attributes>
			<atk value="197"/>
			<def value="28"/>
			<hp value="177"/>
			<speed value="0.9"/>
			<size value="1,1"/>
		</attributes>
		<level value="40"/>
		<experience value="1510"/>
		<respawn value="1610"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[29,39]" probability="20.0"/>
			<item value="elvish shield" quantity="[1,1]" probability="0.5"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>
	<creature name="mountain elf captain">
		<type class="pol/elfy_gorskie" subclass="ae_elf_gorski_lider" tileid="pol_elfy_gorskie.png:6"/>
		<description>You see a seasoned mountain elf captain directing royal defenses.</description>
		<attributes>
			<atk value="205"/>
			<def value="33"/>
			<hp value="176"/>
			<speed value="0.9"/>
			<size value="1,1"/>
		</attributes>
		<level value="44"/>
		<experience value="1710"/>
		<respawn value="1910"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[29,59]" probability="25.0"/>
			<item value="leather enhanced gloves" quantity="[1,1]" probability="30.0"/>
			<item value="elvish sword" quantity="[1,1]" probability="0.5"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="mountain elf warrior">
		<type class="pol/elfy_gorskie" subclass="ae_elf_gorski_wojownik" tileid="pol_elfy_gorskie.png:5"/>
		<description>You see a skilled mountain elf warrior armed with elven steel.</description>
		<attributes>
			<atk value="201"/>
			<def value="31"/>
			<hp value="188"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="44"/>
		<experience value="1610"/>
		<respawn value="1810"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[29,59]" probability="25.0"/>
			<item value="elvish sword" quantity="[1,1]" probability="0.5"/>
			<item value="leather gloves" quantity="[1,1]" probability="2.5"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="mountain elf sorceress">
		<type class="pol/elfy_gorskie" subclass="ae_elf_gorski_czarwonica" tileid="pol_elfy_gorskie.png:11"/>
		<description>You see a mountain elf sorceress weaving elemental enchantments.</description>
		<attributes>
			<atk value="207"/>
			<def value="30"/>
			<hp value="132"/>
			<speed value="0.9"/>
			<size value="1,1"/>
		</attributes>
		<level value="45"/>
		<experience value="2010"/>
		<respawn value="2110"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[29,59]" probability="25.0"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="mountain elf priest">
		<type class="pol/elfy_gorskie" subclass="ae_elf_gorski_kaplan" tileid="pol_elfy_gorskie.png:3"/>
		<description>You see a devout mountain elf priest reciting sacred chants.</description>
		<attributes>
			<atk value="200"/>
			<def value="39"/>
			<hp value="199"/>
			<speed value="0.5"/>
			<size value="1,1"/>
		</attributes>
		<level value="45"/>
		<experience value="1910"/>
		<respawn value="2010"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[29,59]" probability="25.0"/>
			<item value="water" quantity="[1,1]" probability="45.0"/>
			<item value="leather enhanced gloves" quantity="[1,1]" probability="2.5"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="mountain elf warlock">
		<type class="pol/elfy_gorskie" subclass="ae_elf_gorski_czarnoksieznik" tileid="pol_elfy_gorskie.png:2"/>
		<description>You see a mountain elf warlock wielding dark mountain magic.</description>
		<attributes>
			<atk value="201"/>
			<def value="41"/>
			<hp value="198"/>
			<speed value="0.3"/>
			<size value="1,1"/>
		</attributes>
		<level value="46"/>
		<experience value="2110"/>
		<respawn value="2010"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[59,89]" probability="25.0"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="mountain elf queen">
		<type class="pol/elfy_gorskie" subclass="ae_elf_gorski_krolowa" tileid="pol_elfy_gorskie.png:4"/>
		<description>You see the majestic Queen of the mountain elves.</description>
		<attributes>
			<atk value="210"/>
			<def value="38"/>
			<hp value="230"/>
			<speed value="0.8"/>
			<size value="1,1"/>
		</attributes>
		<level value="51"/>
		<experience value="2810"/>
		<respawn value="3010"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[99,189]" probability="5.0"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="mountain elf king">
		<type class="pol/elfy_gorskie" subclass="ae_elf_gorski_krol" tileid="pol_elfy_gorskie.png:8"/>
		<description>You see the noble King of the mountain elves.</description>
		<attributes>
			<atk value="220"/>
			<def value="39"/>
			<hp value="240"/>
			<speed value="0.9"/>
			<size value="1,1"/>
		</attributes>
		<level value="52"/>
		<experience value="2910"/>
		<respawn value="3010"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[99,199]" probability="10.0"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="mountain elf high lord">
		<type class="pol/elfy_gorskie" subclass="ae_elf_gorski_lord" tileid="pol_elfy_gorskie.png:10"/>
		<description>You see the supreme High Lord of the mountain elf realm.</description>
		<attributes>
			<atk value="250"/>
			<def value="49"/>
			<hp value="290"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="59"/>
		<experience value="3110"/>
		<respawn value="3110"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[9,29]" probability="100.0"/>
			<item value="plate gloves" quantity="[1,1]" probability="0.25"/>
			<item value="blue armor" quantity="[1,1]" probability="0.05"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<!-- END: elf gorski -->

</creatures>

=== marcospdsf/EOT/data/conf/creatures/animal_fowl.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="stendhal ../creatures.xsd">

	<creature name="chick">
		<type class="fowl" subclass="chick" tileid="fowl.png:0"/>
		<description>You see a little chick, it doesn't like to be away from its mother.</description>
		<attributes>
			<atk value="32"/>
			<def value="7"/>
			<hp value="25"/>
			<speed value="0.5"/>
			<size value="1,1"/>
		</attributes>
		<level value="1"/>
		<experience value="5"/>
		<respawn value="900"/>
		<corpse name="small_winged" harmless="feathered"/>
		<drops>
			<item value="chicken" quantity="[1,1]" probability="70.0"/>
			<item value="small feather" quantity="[1,1]" probability="50.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<noise state="idle follow fight" value="peep peep"/>
				<noise state="idle follow fight" value="peep peep peep"/>
				<sound value="chicken-chick-1"/>
				<sound value="chicken-chick-2"/>
			</says>
			<profile name="animal"/>
			<profile name="patrolling"/>
			<profile name="coward"/>
		</ai>
	</creature>

	<creature name="chicken">
		<type class="fowl" subclass="chicken" tileid="fowl.png:1"/>
		<description>You see a chicken, isn't it nice?</description>
		<attributes>
			<atk value="32"/>
			<def value="7"/>
			<hp value="25"/>
			<speed value="0.5"/>
			<size value="1,1"/>
		</attributes>
		<level value="1"/>
		<experience value="10"/>
		<respawn value="900"/>
	<corpse name="small_winged" harmless="feathered"/>
		<drops>
			<item value="chicken" quantity="[1,2]" probability="50.0"/>
			<item value="egg" quantity="1" probability="15.0"/>
			<item value="small feather" quantity="[1,2]" probability="60.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<noise state="idle follow fight" value="cluck cluck cluck"/>
				<noise state="idle follow fight" value="cluck cluck"/>
				<sound value="chicken-01"/>
				<sound value="chicken-02"/>
				<sound value="chicken-03"/>
			</says>
			<profile name="animal"/>
			<profile name="patrolling"/>
			<profile name="coward"/>
		</ai>
	</creature>

		<creature name="dodo">
		<type class="fowl" subclass="dodo_bird" tileid="fowl.png:3"/>
		<description>You see a dodo bird, aren't they supposed to be extinct?</description>
		<attributes>
			<atk value="57"/>
			<def value="14"/>
			<hp value="45"/>
			<speed value="0.7"/>
			<size value="1,1"/>
		</attributes>
		<level value="3"/>
		<experience value="30"/>
		<respawn value="900"/>
		<corpse name="small_winged" harmless="feathered"/>
		<drops>
			<item value="chicken" quantity="[1,3]" probability="60.0"/>
			<item value="spinach" quantity="[1,1]" probability="20.0"/>
			<item value="small feather" quantity="[1,3]" probability="70.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<noise state="idle follow fight" value="Bawk Bawk"/>
				<noise state="idle follow fight" value="Bawwwk"/>
				<sound value="bird-dodo-01"/>
			</says>
			<profile name="animal"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="mother hen">
		<type class="fowl" subclass="hen" tileid="fowl.png:2"/>
		<description>You see a mother hen, she will probably hurt you if you touch her sons.</description>
		<attributes>
			<atk value="29"/>
			<def value="6"/>
			<hp value="25"/>
			<speed value="0.7"/>
			<size value="1,1"/>
		</attributes>
		<level value="1"/>
		<experience value="5"/>
		<respawn value="900"/>
		<corpse name="small_winged" harmless="feathered"/>
		<drops>
			<item value="chicken" quantity="[1,2]" probability="70.0"/>
			<item value="egg" quantity="[1,2]" probability="20.0"/>
			<item value="small feather" quantity="[1,2]" probability="60.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<noise state="idle follow fight" value="peep peep"/>
				<noise state="idle follow fight" value="peep peep peep"/>
				<sound value="chicken-01"/>
				<sound value="chicken-02"/>
				<sound value="chicken-03"/>
			</says>
			<profile name="animal"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="penguin">
		<type class="fowl" subclass="penguin" tileid="fowl.png:5"/>
		<description>You see a penguin, smart and silly.</description>
		<attributes>
			<atk value="36"/>
			<def value="7"/>
			<hp value="20"/>
			<speed value="0.5"/>
			<size value="1,1"/>
		</attributes>
		<level value="1"/>
		<experience value="10"/>
		<respawn value="900"/>
		<corpse name="small_animal" harmless="feathered"/>
		<drops>
			<item value="chicken" quantity="[2,4]" probability="60.0"/>
			<item value="cod" quantity="[2,3]" probability="30.0"/>
			<item value="small feather" quantity="[1,2]" probability="50.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<noise state="idle follow fight" value="Oou! Oou!"/>
				<noise state="idle follow fight" value="*flap* *flap*"/>
				<sound value="penguin-1"/>
				<sound value="penguin-2"/>
			</says>
			<profile name="animal"/>
			<profile name="offensive"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="pigeon">
		<type class="fowl" subclass="pigeon" tileid="fowl.png:4"/>
		<description>You see a pigeon, it loves the little seeds.</description>
		<attributes>
			<atk value="36"/>
			<def value="7"/>
			<hp value="20"/>
			<speed value="0.5"/>
			<size value="1,1"/>
		</attributes>
		<level value="1"/>
		<experience value="10"/>
		<respawn value="900"/>
		<corpse name="small_winged" harmless="feathered"/>
		<drops>
			<item value="chicken" quantity="[1,2]" probability="40.0"/>
			<item value="small feather" quantity="[1,2]" probability="60.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<sound value="bird-pigeon-1"/>
				<sound value="bird-pigeon-flap-1"/>
			</says>
			<profile name="animal"/>
			<profile name="patrolling"/>
			<profile name="coward"/>
		</ai>
	</creature>

</creatures>

=== marcospdsf/EOT/data/conf/creatures/faumonia_balourghy.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../creatures.xsd ">

	<creature name="balourgh warrior">
		<type class="balourg" subclass="1" tileid="faumonia_balourgh.png:0"/>
		<description>You see a balourgh warrior encased in heavy plated armor.</description>
		<attributes>
			<atk value="924"/>
			<def value="47"/>
			<hp value="600"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="130"/>
		<experience value="8370"/>
		<respawn value="4500"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[12,25]" probability="70.0"/>
			<item value="water" quantity="[1,3]" probability="70.0"/>
			<item value="balourg armor" quantity="[1,1]" probability="0.5"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<profile name="offensive"/>
			<profile name="coward"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>
	
	<creature name="balourgh soldier">
		<type class="balourg" subclass="2" tileid="faumonia_balourgh.png:1"/>
		<description>You see a disciplined balourgh soldier clad in thick carapace.</description>
		<attributes>
			<atk value="934"/>
			<def value="48"/>
			<hp value="640"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="132"/>
		<experience value="8070"/>
		<respawn value="4600"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[12,25]" probability="70.0"/>
			<item value="water" quantity="[1,3]" probability="70.0"/>
			<item value="balourg armor" quantity="[1,1]" probability="0.5"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<profile name="offensive"/>
			<profile name="coward"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>
	
	<creature name="balourgh captain">
		<type class="balourg" subclass="3" tileid="faumonia_balourgh.png:2"/>
		<description>You see a balourgh captain commanding vanguard ranks.</description>
		<attributes>
			<atk value="944"/>
			<def value="47"/>
			<hp value="600"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="134"/>
		<experience value="8140"/>
		<respawn value="4800"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[12,25]" probability="70.0"/>
			<item value="water" quantity="[1,3]" probability="70.0"/>
			<item value="balourg armor" quantity="[1,1]" probability="0.5"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<profile name="offensive"/>
			<profile name="coward"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>
	
	<creature name="balourgh commander">
		<type class="balourg" subclass="4" tileid="faumonia_balourgh.png:3"/>
		<description>You see a veteran balourgh commander trained in combat since youth.</description>
		<attributes>
			<atk value="994"/>
			<def value="50"/>
			<hp value="750"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="142"/>
		<experience value="8840"/>
		<respawn value="5000"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[18,45]" probability="70.0"/>
			<item value="water" quantity="[1,3]" probability="70.0"/>
			<item value="balourg armor" quantity="[1,1]" probability="0.5"/>
			<item value="balourg cloak" quantity="[1,1]" probability="1.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<profile name="offensive"/>
			<profile name="coward"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

</creatures>
